FROM node:22-slim
WORKDIR /app
COPY package.json deno.lock* ./
RUN npm install
COPY . .
ARG VITE_ANALYTICS_ID
ARG VITE_ANALYTICS_SRC
ENV VITE_ANALYTICS_ID=$VITE_ANALYTICS_ID
ENV VITE_ANALYTICS_SRC=$VITE_ANALYTICS_SRC
RUN npm run build
EXPOSE 8000
CMD ["node", "serve.js"]
